<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "galerie_lstbdd"
 *
 * Auto generated by Extension Builder 2019-06-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Galerie_lstbdd',
    'description' => 'Galerie d\'image pour un projet étudiant DAWIN',
    'category' => 'plugin',
    'author' => 'Loïc BITTER, Tony DUONG, Sylvain DUPUY',
    'author_email' => 'loic.bitter@etu.u-bordeaux.fr, tony.duong@etu.u-bordeaux.fr, sylvain.dupuy@etu.u-bordeaux.fr',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
